---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - assets:
      - path: lenra-api.zip
        name: lenra-api-${nextRelease.gitTag}.zip
      - path: lenra-api.tar.gz
        name: lenra-api-${nextRelease.gitTag}.tar.gz
      # TODO: add Licence and README ?