---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: docs
          scope: api
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - assets:
        - path: lenra-api.zip
          name: lenra-api-${nextRelease.gitTag}.zip
        - path: lenra-api.tar.gz
          name: lenra-api-${nextRelease.gitTag}.tar.gz
        - path: lenra-api-docs/lenra-api-docs.zip
          name: lenra-api-docs-${nextRelease.gitTag}.zip
        - path: lenra-api-docs/lenra-api-docs.tar.gz
          name: lenra-api-docs-${nextRelease.gitTag}.tar.gz
      # TODO: add Licence and README ?
