name: Generate doc artifact
on:
  push:
    branches:
      - main
      - beta
      - "*.x"
jobs:
  release:
    name: Generate doc artifact
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup node deps
        run: |
          cd docs
          npm i
          npm run build
      - name: Compress tar.gz
        run: tar czvf lenra-api-docs.tar.gz docs/build/
      - name: Compress zip
        run: zip -r lenra-api-docs.zip docs/build/
