name: Release
on:
  push:
    branches:
      - main
      - beta
      - "*.x"
jobs:
  generate_doc_artifact:
    name: Generate doc artifact
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Setup node deps
        run: |
          cd docs
          npm i
          cd node_modules/mdx2html
          node build.js bin/**/*.jsx
          npm i -g .
          cd ../..
          npm run build
      - name: Compress tar.gz
        run: tar czvf lenra-api-docs.tar.gz docs/build/
      - name: Compress zip
        run: zip -r lenra-api-docs.zip docs/build/
      - name: Documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: lenra-api-docs
          path: |
            lenra-api-docs.tar.gz
            lenra-api-docs.zip
  release:
    needs: generate_doc_artifact
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup node deps
        run: npm i conventional-changelog-conventionalcommits@5 -D
      - name: Compress tar.gz
        run: tar czvf lenra-api.tar.gz api/
      - name: Compress zip
        run: zip -r lenra-api.zip api/

      - name: download-artifacts
        uses: actions/download-artifact@v3
        with:
          name: lenra-api-docs
          path: |
            lenra-api-docs.tar.gz
            lenra-api-docs.zip
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        run: npx semantic-release@18
